import { Sparkles } from "lucide-react";
import type { NarrativeResult } from "@/lib/types";

export function ExecutiveSummaryCard({
  narrative,
  narrativeError,
}: {
  narrative: NarrativeResult | null;
  narrativeError?: string | null;
}) {
  return (
    <div className="relative rounded-xl border border-signal/25 bg-gradient-to-br from-signal/[0.06] to-transparent p-6">
      <div className="flex items-center gap-2 mb-4">
        <Sparkles className="w-4 h-4 text-signal" strokeWidth={2} />
        <h3 className="mono-label text-[11px] text-signal">AI Executive Summary</h3>
      </div>

      {narrative ? (
        <>
          <p className="text-sm leading-relaxed text-text-primary/90">{narrative.summary}</p>
          {narrative.recommendations.length > 0 && (
            <div className="mt-5 pt-5 border-t border-hairline">
              <p className="mono-label text-[10px] text-text-muted mb-2.5">Recommended Actions</p>
              <ul className="space-y-2">
                {narrative.recommendations.map((rec, i) => (
                  <li key={i} className="flex gap-2.5 text-sm text-text-primary/90">
                    <span className="text-signal shrink-0">→</span>
                    <span>{rec}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
          <p className="mt-4 text-[10px] font-mono text-text-muted">
            Generated by {narrative.model} · {new Date(narrative.generatedAt).toLocaleString()}
          </p>
        </>
      ) : (
        <p className="text-sm text-text-muted">
          {narrativeError ??
            "AI narrative wasn't generated for this run — check your API key configuration and re-process the file."}
        </p>
      )}
    </div>
  );
}
